CREATE TABLE Posts(
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL,
  description VARCHAR(255) NOT NULL,
  commments INTEGER NOT NULL,
  likes INTEGER NOT NULL,
  FOREIGN KEY(user_id) REFERENCES Users(id)
)